name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm ci
    - name: Check Package Security
      run: npm audit
    - name: Check Coding Guidelines
      run: npm run lint
    - name: Production Build
      run: npm run build
    - name: Test
      run: npm run test
